@extends('layouts.superadmin')

@section('title', 'Detail Tenant')
@section('page_title', 'Detail Tenant')
@section('page_subtitle', 'Informasi dan performa Tenant.')

@section('content')
<div class="bg-white rounded-3xl border border-slate-100 shadow-sm p-8 mb-6"><div class="flex items-center gap-5 mb-8"><img src="{{ $tenant->logo_url ?: 'https://ui-avatars.com/api/?name=' . urlencode($tenant->name) }}" class="w-20 h-20 rounded-2xl object-cover"><div><h2 class="text-2xl font-black">{{ $tenant->name }}</h2><p class="text-slate-500">{{ $tenant->user->name }} · {{ $tenant->email ?: $tenant->user->email }}</p></div></div>
	<div class="grid md:grid-cols-2 lg:grid-cols-4 gap-4"><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Status Tenant</p><p class="font-bold mt-2">{{ $status }}</p></div><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Tanggal Bergabung</p><p class="font-bold mt-2">{{ $tenant->created_at?->format('d M Y') ?? '-' }}</p></div><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Jumlah Event</p><p class="font-bold mt-2">{{ $tenant->events->count() }}</p></div><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Total Tiket Terjual</p><p class="font-bold mt-2">{{ number_format($totalTicketsSold, 0, ',', '.') }}</p></div></div>
	<div class="grid md:grid-cols-2 gap-4 mt-4"><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Nomor HP</p><p class="font-bold mt-2">{{ $phone ?: '-' }}</p></div><div class="p-5 bg-slate-50 rounded-2xl"><p class="text-xs uppercase font-bold text-slate-400">Alamat</p><p class="font-bold mt-2">{{ $address ?: '-' }}</p></div></div><p class="mt-5 font-black text-indigo-600">Total Pendapatan: Rp {{ number_format($totalRevenue, 0, ',', '.') }}</p>
	<div class="mt-6 flex flex-wrap gap-3">@if($status === \App\Models\User::STATUS_SUSPENDED)<form method="POST" action="{{ route('superadmin.tenants.activate', $tenant) }}" onsubmit="return confirm('Aktifkan Tenant ini kembali?')">@csrf<button class="px-5 py-3 rounded-2xl bg-green-600 text-white font-bold hover:bg-green-700">Aktifkan Tenant</button></form>@else<form method="POST" action="{{ route('superadmin.tenants.suspend', $tenant) }}" onsubmit="return confirm('Suspend Tenant ini? Tenant tidak dapat login atau mengelola event.')">@csrf<button class="px-5 py-3 rounded-2xl bg-rose-600 text-white font-bold hover:bg-rose-700">Suspend Tenant</button></form>@endif<a href="{{ route('superadmin.tenants.index') }}" class="px-5 py-3 rounded-2xl border border-slate-200 text-slate-700 font-bold hover:bg-slate-50">Kembali</a></div>
</div>
<div class="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden"><div class="p-8 border-b"><h3 class="font-black text-xl">Daftar Event Tenant</h3></div><div class="divide-y">@forelse($tenant->events as $event)<div class="px-8 py-5 flex justify-between gap-4"><span class="font-bold">{{ $event->title }}</span><span class="text-slate-500">{{ $event->category->name ?? '-' }} · {{ $event->date?->format('d M Y') ?? '-' }}</span></div>@empty<div class="p-8 text-center text-slate-400">Belum ada event yang terhubung.</div>@endforelse</div></div>
@endsection
